pipeline:
  name: summarize-vector-search-pipeline
  modules:
  - name: summarize
    models:
    - name: bart-large-cnn
    - name: text-summarization
    defaults:
      model: bart-large-cnn
    input:
      type: text
      permitted_extensions:
      - .txt
      - .pdf
      - .docx
      - .pptx
    output:
      type: json
  - name: json-to-txt
    models:
    - name: base
    defaults:
      model: base
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: text
  - name: parser
    models:
    - name: fixed
      params:
        chunk_size:
          type: int
        overlap_size:
          type: int
    defaults:
      model: fixed
    input:
      type: text
      permitted_extensions:
      - .txt
      - .pdf
      - .docx
      - .pptx
    output:
      type: json
  - name: text-embedder
    models:
    - name: multi-qa-MiniLM-L6-cos-v1
      params:
        quantize:
          type: bool
    - name: msmarco-distilbert-dot-v5
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L12-v2
      params:
        quantize:
          type: bool
    - name: all-mpnet-base-v2
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L6-v2
      params:
        quantize:
          type: bool
    defaults:
      model: multi-qa-MiniLM-L6-cos-v1
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: npy
  - name: vector-search
    models:
    - name: faiss
    defaults:
      model: faiss
    input:
      type: npy
      permitted_extensions:
      - .npy
    output:
      type: faiss
