pipeline:
  name: translate-vector-search-pipeline
  modules:
  - name: translate
    models:
    - name: opus-mt-de-en
    - name: opus-mt-en-es
    - name: opus-mt-en-fr
    - name: opus-mt-fr-en
    - name: opus-mt-it-en
    - name: opus-mt-zh-en
    defaults:
      model: opus-mt-en-es
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: json
  - name: text-embedder
    models:
    - name: multi-qa-MiniLM-L6-cos-v1
      params:
        quantize:
          type: bool
    - name: msmarco-distilbert-dot-v5
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L12-v2
      params:
        quantize:
          type: bool
    - name: all-mpnet-base-v2
      params:
        quantize:
          type: bool
    - name: all-MiniLM-L6-v2
      params:
        quantize:
          type: bool
    defaults:
      model: multi-qa-MiniLM-L6-cos-v1
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: npy
  - name: vector-search
    models:
    - name: faiss
    defaults:
      model: faiss
    input:
      type: npy
      permitted_extensions:
      - .npy
    output:
      type: faiss
