pipeline:
  name: translate-pipeline
  modules:
  - name: translate
    models:
    - name: opus-mt-de-en
    - name: opus-mt-en-es
    - name: opus-mt-en-fr
    - name: opus-mt-fr-en
    - name: opus-mt-it-en
    - name: opus-mt-zh-en
    defaults:
      model: opus-mt-en-es
    input:
      type: json
      permitted_extensions:
      - .json
    output:
      type: json
